### ISSUE TITLE
Rebranding error in CONTRIBUTING.md

### ISSUE THREAD

**Issue by Prestonion** [jamen/neta#21]
Line 14 of CONTRIBUTING.md, we are still using the name Campfire instead of Neta.

Also, I believe we aren't using Vue anymore, and are switching to React. Unless we are still going to use Vue, it needs to be changed.

**Comment by jamen** [comment]
@Prestonion, I made a PR (#22), but I'm at school so I can't test it.  If you can test it (and merge if it works) that would be great.  Otherwise I'll test it when I get home.

**Comment by jamen** [comment]
I would also like the note that the majority of the Wiki pages still use "Campfire".  I can work on that.
